### ISSUE TITLE
Solution Stuck on "Submitted"

### ISSUE THREAD

**Issue by JasonMendoza2008** [codalab/codabench#1507]
Submission stuck on Submitted. It happens randomly. **I had to cancel last time after several hours but it counted towards my quota**. What can I do:
<img width="874" alt="image" src="https://github.com/codalab/codabench/assets/56092290/4b2a9744-3c9a-4a68-a45a-6baca7f4c4a4">

My username is jmendoza2008 on Codabench

**Comment by ihsaan-ullah** [comment]
Your submission is not cancelled, its status is submitted. Only cancelled and failed submissions are not counted in the quota.

**Comment by JasonMendoza2008** [comment]
I know I'm saying last time I had to cancel and this time it's just stuck so I'm worrying I might have to cancel it too.

**Comment by JasonMendoza2008** [comment]
Cancelled submissions are counted in the quota.

**Comment by JasonMendoza2008** [comment]
@ihsaan-ullah 
I know I'm saying last time I had to cancel (this is what I meant in my initial message by "I had to cancel last time after several hours") and this time it's just stuck so I'm worrying I might have to cancel it too.

**Comment by JasonMendoza2008** [comment]
@ihsaan-ullah 
Cancelled submissions are counted in the quota.

**Comment by ihsaan-ullah** [comment]
> @ihsaan-ullah Cancelled submissions are counted in the quota.

my mistake, cancelled are indeed counted in the quota

**Comment by ihsaan-ullah** [comment]
Not sure why your submission is stuck in submitted. I reran your submission. It seems to be working now

**Comment by JasonMendoza2008** [comment]
Yes I saw. Thank you very much for your help.

**Comment by JasonMendoza2008** [comment]
I'm sorry @ihsaan-ullah, but my submission is again stuck:
<img width="861" alt="image" src="https://github.com/codalab/codabench/assets/56092290/7f40afa2-b7de-4999-acf1-c63468efacf4">

I hope I'm not doing something wrong?
Here is the content of my submission in case that's useful to you:
[my_submission.zip](https://github.com/user-attachments/files/16041834/my_submission.zip)

**Comment by JasonMendoza2008** [comment]
Would love to know if I can submit other submissions (it's still stuck 48 hours later and I don't want to break anything on codabench by submitting before this submission is dealt with)

**Comment by Didayolo** [comment]
Hi,

The problem you are encountering was fixed here: #1503

We still need to deploy this change. It should be done later today.

**Comment by Didayolo** [comment]
Deployed! Feel free to re-open the issue if you encounter it again.

**Comment by JasonMendoza2008** [comment]
@Didayolo you might want to close https://github.com/codalab/codabench/issues/1509 too

**Comment by JasonMendoza2008** [comment]
The issue is not resolved @Didayolo 
<img width="868" alt="image" src="https://github.com/codalab/codabench/assets/56092290/fe3529c1-0a43-40f8-a178-531b1e3ac563">

**Comment by Didayolo** [comment]
Hi @JasonMendoza2008,

Can you please share the URL of the competition and your username?

**Comment by JasonMendoza2008** [comment]
@Didayolo https://www.codabench.org/competitions/3188 and jmendoza2008

**Comment by Didayolo** [comment]
OK so this competition is using the public queue, not a private queue. The problem may be related to:

- #1446

I see that some submissions after this one did succeed.

**Comment by JasonMendoza2008** [comment]
Yes it randomly fails and I have to re-submit.

**Comment by sourabhd13** [comment]
We are also facing a similar issue. Multiple submissions are stuck at various stages (Scoring, Submitting) for a long time. My username is sourabhd.

**Comment by Didayolo** [comment]
Any update on this?
